#!/usr/bin/env python3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
PLAY=ROOT/'app/src/main/java/ru/gran/edge2e/ReferencePlayActivity.java'

def method(path,marker,new):
 s=path.read_text(encoding='utf-8');start=s.find(marker)
 if start<0: raise SystemExit(f'9.1 method not found: {marker}')
 brace=s.find('{',start);depth=0;ins=inc=esc=False;end=-1
 for i in range(brace,len(s)):
  c=s[i]
  if esc: esc=False;continue
  if c=='\\' and (ins or inc): esc=True;continue
  if c=='"' and not inc: ins=not ins;continue
  if c=="'" and not ins: inc=not inc;continue
  if ins or inc: continue
  if c=='{': depth+=1
  elif c=='}':
   depth-=1
   if depth==0:end=i+1;break
 if end<0: raise SystemExit(f'9.1 closing brace not found: {marker}')
 path.write_text(s[:start]+new.strip()+s[end:],encoding='utf-8')

method(PLAY,'private LinearLayout spellsPage()',r'''private LinearLayout spellsPage(){
 LinearLayout col=page();col.addView(section("ЗАКЛИНАНИЯ"));SpellcastingRules.Profile profile=SpellcastingRules.resolve(state,runtime);if(profile==null){LinearLayout empty=panel();empty.addView(text("Нет активного источника заклинаний",17,true));empty.addView(note("Выбери класс или особенность с заклинаниями в СБОРКЕ."));col.addView(empty,matchWrap(dp(4)));return col;}RuleItem cls=classItem();LinearLayout head=panel();LinearLayout metrics=row();metrics.addView(metricBox("КС",String.valueOf(DerivedStats.spellDc(state,stats,cls))),weighted(dp(1)));metrics.addView(metricBox("АТАКА",signed(DerivedStats.spellAttack(state,stats,cls))),weighted(dp(1)));metrics.addView(metricBox("ТРАДИЦИЯ",SpellcastingRules.traditionLabel(profile.tradition)),weighted(dp(1)));head.addView(metrics);head.addView(note(RuNames.shortName(profile.source)+" • "+SpellcastingRules.modeLabel(profile)));if(!profile.note.isEmpty())head.addView(note(profile.note));col.addView(head,matchWrap(dp(4)));addFocusAndRitualSections(col);if(!profile.supported)return col;spellState.sanitize(profile,state.level);
 for(int rank=1;rank<=profile.maxRank(state.level);rank++){int slots=SpellcastingRules.PREPARED.equals(profile.mode)?profile.totalPreparedSlots(state.level,rank):profile.slots(state.level,rank);if(slots<=0)continue;col.addView(section("РАНГ "+rank));LinearLayout block=panel();if(SpellcastingRules.PREPARED.equals(profile.mode)){for(int slot=0;slot<slots;slot++){final int rr=rank,ss=slot;String name=spellState.preparedName(rank,slot);boolean spent=spellState.preparedSpent(rank,slot);LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(8),dp(6),dp(8),dp(6));r.setBackground(round(PANEL_2,0,PANEL_2));r.setContentDescription("spell-slot-"+rank+"-"+slot);r.setClickable(true);r.setFocusable(true);TextView main=text(name.isEmpty()?"Подготовить заклинание":RuNames.shortName(name),13,true);main.setTextColor(spent?MUTED:TEXT);r.addView(main,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));r.addView(badge(String.valueOf(slot+1),spent?MUTED:ACCENT));TextView used=text(spent?"  ИСП.":"",9,true);used.setTextColor(MUTED);r.addView(used);r.setOnClickListener(v->{if(spellState.preparedId(rr,ss).isEmpty())showSpellPicker(profile,rr,item->{spellState.prepare(rr,ss,item);spellState.save(this);render();});else{spellState.setPreparedSpent(rr,ss,!spellState.preparedSpent(rr,ss));spellState.save(this);render();}});r.setOnLongClickListener(v->{spellState.prepare(rr,ss,null);spellState.save(this);render();return true;});block.addView(r,matchWrap(dp(1)));}}else{int spent=spellState.spent(rank);LinearLayout slotsRow=row();slotsRow.addView(metricBox("ДОСТУПНО",String.valueOf(slots-spent)),weighted(dp(1)));slotsRow.addView(metricBox("ВСЕГО",String.valueOf(slots)),weighted(dp(1)));block.addView(slotsRow);final int rr=rank;LinearLayout useRow=row();Button use=button("ИСПОЛЬЗОВАТЬ СЛОТ"),restore=button("ВОССТАНОВИТЬ");use.setOnClickListener(v->{spellState.spend(rr,slots);spellState.save(this);render();});restore.setOnClickListener(v->{spellState.restoreOne(rr,slots);spellState.save(this);render();});useRow.addView(use,weighted(dp(2)));useRow.addView(restore,weighted(dp(2)));block.addView(useRow);for(SpellcastingState.RepertoireSpell sp:spellState.repertoire(rank)){TextView row=actionRow((spellState.isSignature(rank,sp.id)?"★ ":"")+RuNames.shortName(sp.name),spellState.isSignature(rank,sp.id)?"ключевое":"репертуар");row.setOnClickListener(v->{spellState.setSignature(rr,sp.id);spellState.save(this);render();});block.addView(row);}TextView add=actionRow("+ ДОБАВИТЬ ЗАКЛИНАНИЕ","репертуар ранга "+rank);add.setOnClickListener(v->showSpellPicker(profile,rr,item->{spellState.addRepertoire(rr,item);spellState.save(this);render();}));block.addView(add);}col.addView(block,matchWrap(dp(4)));}return col;
}''')

method(PLAY,'private LinearLayout gearPage()',r'''private LinearLayout gearPage(){
 LinearLayout col=page();col.addView(section("СНАРЯЖЕНИЕ"));BulkRules.Summary bulk=BulkRules.calculate(store,state,stats,inventory);LinearLayout summary=panel();summary.addView(statsRow(new String[][]{{"ЗМ",String.valueOf(inventory.gp)},{"СМ",String.valueOf(inventory.sp)},{"ММ",String.valueOf(inventory.cp)},{"BULK",BulkRules.label(bulk.totalLight)}}));summary.addView(note("Нагрузка: "+bulk.status()));col.addView(summary,matchWrap(dp(4)));List<RuleItem> items=inventoryItems();String[][] groups={{"ОРУЖИЕ","weapon"},{"БРОНЯ И ЩИТЫ","defense"},{"ПРОЧЕЕ СНАРЯЖЕНИЕ","other"}};for(String[] group:groups){col.addView(section(group[0]));LinearLayout list=panel();int count=0;for(RuleItem item:items){boolean match="weapon".equals(group[1])&&"weapon".equalsIgnoreCase(item.subtype)||"defense".equals(group[1])&&("armor".equalsIgnoreCase(item.subtype)||"shield".equalsIgnoreCase(item.subtype))||"other".equals(group[1])&&!("weapon".equalsIgnoreCase(item.subtype)||"armor".equalsIgnoreCase(item.subtype)||"shield".equalsIgnoreCase(item.subtype));if(!match)continue;count++;int qty=inventory.quantity(item.id);String container=inventory.containerFor(item.id);String meta=translatedSubtype(item.subtype)+" • "+BulkRules.itemBulkLabel(item,qty)+(qty>1?" • ×"+qty:"")+(!container.isEmpty()?" • в контейнере":"");TextView row=actionRow(RuNames.shortName(item.name),meta);row.setOnClickListener(v->equipmentDialog(item));list.addView(row);}if(count==0)list.addView(note("Нет предметов этого типа."));col.addView(list,matchWrap(dp(3)));}col.addView(section("ДОБАВИТЬ"));LinearLayout addBlock=panel();TextView add=actionRow("+ ДОБАВИТЬ ПРЕДМЕТ","оружие, броня, расходники, инструменты");add.setContentDescription("gear-add-item");add.setOnClickListener(v->showEquipmentPicker());addBlock.addView(add);col.addView(addBlock,matchWrap(dp(4)));if(!bulk.containers.isEmpty()){col.addView(section("КОНТЕЙНЕРЫ"));LinearLayout containers=panel();for(BulkRules.ContainerLoad load:bulk.containers)containers.addView(pair(RuNames.shortName(load.item.name),BulkRules.label(load.countedContentsLight)+(load.capacityLight>0?" / "+BulkRules.label(load.capacityLight):"")+(load.overCapacity?" • ПЕРЕПОЛНЕН":"")));col.addView(containers,matchWrap(dp(4)));}return col;
}''')

s=PLAY.read_text(encoding='utf-8');s=s.replace('LinearLayout help = panel(); help.addView(note("Спутники разделены по типам так же, как в эталонном PLAY: животные-компаньоны, фамильяры, эйдолоны, конструкты и последователи.")); col.addView(help, matchWrap(dp(4)));','');PLAY.write_text(s,encoding='utf-8')
print('Gran 2e 9.1 specialized PLAY pages applied')
