package ru.gran.edge2e;

import android.app.Activity;
import android.app.AlertDialog;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

/** Dedicated editor for animal companions, familiars, eidolons, constructs and followers. */
public final class ReferenceCompanionActivity extends Activity {
    private static final int BG=Color.rgb(232,231,227),TOP=Color.rgb(55,57,59),PANEL=Color.rgb(250,250,248),PANEL2=Color.rgb(241,241,237),BORDER=Color.rgb(188,188,183),TEXT=Color.rgb(36,37,38),MUTED=Color.rgb(103,105,107),ACCENT=Color.rgb(121,31,44),BAD=Color.rgb(176,54,54);
    private CompanionState state; private CompanionState.Companion companion; private LinearLayout body;

    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(TOP);load();setContentView(shell());render();}
    @Override protected void onResume(){super.onResume();if(body!=null){load();render();}}
    private void load(){state=CompanionState.load(this);String id=getIntent()==null?"":getIntent().getStringExtra("companionId");companion=null;for(CompanionState.Companion c:state.items)if(c.id.equals(id)){companion=c;break;}}

    private View shell(){LinearLayout root=column();root.setBackgroundColor(BG);LinearLayout top=row();top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(12),dp(9),dp(12),dp(9));top.setBackgroundColor(TOP);TextView back=text("‹ ПИТОМЦЫ",11,true);back.setTextColor(Color.WHITE);back.setPadding(0,dp(5),dp(12),dp(5));back.setOnClickListener(v->finish());top.addView(back);TextView title=text("СПУТНИК",18,true);title.setTextColor(Color.WHITE);top.addView(title,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));root.addView(top,matchWrap());ScrollView sv=new ScrollView(this);body=column();body.setPadding(dp(10),dp(8),dp(10),dp(30));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));return root;}

    private void render(){body.removeAllViews();if(companion==null){LinearLayout p=panel();p.addView(text("Спутник не найден",17,true));body.addView(p);return;}
        LinearLayout head=panel();TextView n=text(companion.name,22,true);n.setTextColor(ACCENT);head.addView(n);head.addView(note(companion.type+" • ур. "+companion.level));TextView edit=actionRow("ИМЯ И ТИП","редактировать профиль");edit.setOnClickListener(v->editIdentity());head.addView(edit);body.addView(head,matchWrap(dp(4)));
        body.addView(section("БОЕВЫЕ ПАРАМЕТРЫ"));LinearLayout stats=panel();stats.addView(stepper("Уровень",companion.level,1,20,v->{companion.level=v;save();}));stats.addView(stepper("ОЗ",companion.hp,0,Math.max(1,companion.maxHp),v->{companion.hp=v;save();}));stats.addView(stepper("Макс. ОЗ",companion.maxHp,1,999,v->{companion.maxHp=v;companion.hp=Math.min(companion.hp,v);save();}));stats.addView(stepper("КД",companion.ac,1,60,v->{companion.ac=v;save();}));stats.addView(stepper("Атака",companion.attack,-20,60,v->{companion.attack=v;save();}));TextView dmg=actionRow("УРОН",companion.damage);dmg.setOnClickListener(v->editText("Урон",companion.damage,x->{companion.damage=x;save();}));stats.addView(dmg);body.addView(stats,matchWrap(dp(4)));
        body.addView(section(sectionName()));LinearLayout abilities=panel();abilities.addView(note(typeHint()));TextView notes=actionRow("СПОСОБНОСТИ / ЗАМЕТКИ",companion.notes.isEmpty()?"добавить":companion.notes);notes.setOnClickListener(v->editText("Способности и заметки",companion.notes,x->{companion.notes=x;save();}));abilities.addView(notes);body.addView(abilities,matchWrap(dp(4)));
        Button remove=button("УДАЛИТЬ СПУТНИКА");remove.setTextColor(BAD);remove.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Удалить спутника?").setMessage(companion.name).setNegativeButton("Отмена",null).setPositiveButton("Удалить",(d,w)->{state.remove(companion.id);state.save(this);finish();}).show());body.addView(remove,matchWrap(dp(8)));
    }

    private String sectionName(){if("Фамильяр".equalsIgnoreCase(companion.type))return"СПОСОБНОСТИ ФАМИЛЬЯРА";if("Эйдолон".equalsIgnoreCase(companion.type))return"ЭЙДОЛОН: АТАКИ И ЭВОЛЮЦИЯ";if("Животный-компаньон".equalsIgnoreCase(companion.type))return"СПЕЦИАЛИЗАЦИЯ КОМПАНЬОНА";if("Конструкт".equalsIgnoreCase(companion.type))return"МОДИФИКАЦИИ КОНСТРУКТА";return"ОСОБЕННОСТИ ПОСЛЕДОВАТЕЛЯ";}
    private String typeHint(){if("Фамильяр".equalsIgnoreCase(companion.type))return"Запиши способности фамильяра, мастер-способности и особые действия. Они сохраняются отдельно для этого персонажа.";if("Эйдолон".equalsIgnoreCase(companion.type))return"Здесь хранятся особенности эйдолона, формы атак, тип урона и выбранные эволюции.";if("Животный-компаньон".equalsIgnoreCase(companion.type))return"Укажи специализацию, поддержку и зрелость компаньона; боевые значения редактируются выше.";if("Конструкт".equalsIgnoreCase(companion.type))return"Укажи модификации, типы атак и конструктивные особенности.";return"Особенности, действия и игровые заметки спутника.";}

    private void editIdentity(){LinearLayout p=column();p.setPadding(dp(10),dp(5),dp(10),dp(5));EditText name=input("Имя");name.setText(companion.name);p.addView(name);String[] types={"Животный-компаньон","Фамильяр","Эйдолон","Конструкт","Последователь"};TextView type=actionRow("ТИП",companion.type);p.addView(type);final int[] selected={index(types,companion.type)};type.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Тип спутника").setSingleChoiceItems(types,selected[0],(d,w)->{selected[0]=w;type.setText("ТИП\n"+types[w]);d.dismiss();}).show());new AlertDialog.Builder(this).setTitle("ПРОФИЛЬ СПУТНИКА").setView(p).setPositiveButton("Сохранить",(d,w)->{companion.name=name.getText().toString().trim().isEmpty()?companion.type:name.getText().toString().trim();companion.type=types[Math.max(0,selected[0])];save();render();}).setNegativeButton("Отмена",null).show();}
    private static int index(String[] a,String s){for(int i=0;i<a.length;i++)if(a[i].equalsIgnoreCase(s))return i;return 0;}
    private void editText(String title,String current,StringSetter setter){EditText e=input(title);e.setSingleLine(false);e.setMinLines(4);e.setText(current);new AlertDialog.Builder(this).setTitle(title).setView(e).setPositiveButton("Сохранить",(d,w)->{setter.set(e.getText().toString());render();}).setNegativeButton("Отмена",null).show();}
    private void save(){state.save(this);}private interface StringSetter{void set(String s);}private interface IntSetter{void set(int v);}
    private View stepper(String label,int value,int min,int max,IntSetter setter){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(4),dp(5),dp(4),dp(5));TextView l=text(label,14,true);r.addView(l,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));Button minus=smallButton("−");TextView val=text(String.valueOf(value),17,true);val.setGravity(Gravity.CENTER);val.setMinWidth(dp(52));Button plus=smallButton("+");minus.setOnClickListener(v->{setter.set(Math.max(min,value-1));render();});plus.setOnClickListener(v->{setter.set(Math.min(max,value+1));render();});r.addView(minus);r.addView(val);r.addView(plus);return r;}
    private TextView actionRow(String a,String b){TextView v=text(a+"\n"+b,14,false);v.setPadding(dp(10),dp(8),dp(10),dp(8));v.setBackground(round(PANEL2,6,BORDER));LinearLayout.LayoutParams p=matchWrap(dp(2));v.setLayoutParams(p);return v;}private TextView section(String s){TextView v=text(s,12,true);v.setTextColor(ACCENT);v.setPadding(dp(3),dp(10),dp(3),dp(5));return v;}private TextView note(String s){TextView v=text(s,12,false);v.setTextColor(MUTED);v.setPadding(0,dp(4),0,0);return v;}
    private LinearLayout panel(){LinearLayout l=column();l.setPadding(dp(9),dp(8),dp(9),dp(8));l.setBackground(round(PANEL,8,BORDER));return l;}private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}private TextView text(String s,int size,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(TEXT);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}private EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(MUTED);e.setTextColor(TEXT);e.setBackground(round(PANEL2,6,BORDER));e.setPadding(dp(10),dp(8),dp(10),dp(8));return e;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(ACCENT);b.setBackground(round(PANEL2,7,BORDER));return b;}private Button smallButton(String s){Button b=button(s);b.setTextSize(17);b.setMinWidth(dp(46));b.setMinimumHeight(0);b.setMinHeight(dp(38));return b;}private GradientDrawable round(int c,int r,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),stroke);return g;}private LinearLayout.LayoutParams matchWrap(){return new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);}private LinearLayout.LayoutParams matchWrap(int m){LinearLayout.LayoutParams p=matchWrap();p.setMargins(0,m,0,m);return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
